import{i as u,a as h,S as v}from"./assets/vendor-Rdv7LHNr.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(o){if(o.ep)return;o.ep=!0;const n=a(o);fetch(o.href,n)}})();function i(t,r){u.info({message:`${t}`,position:"topRight",backgroundColor:`${r}`})}const e={form:document.querySelector(".search-form"),gallery:document.querySelector(".gallery"),div:document.createElement("div"),loadMoreBtn:document.querySelector(".load-more-btn"),API_KEY:"46342237-7f01d30a27b9cd655db8e01c6",BASE_URL:"https://pixabay.com/api/?",eventType:"",queryString:"",currentPage:1,options:{method:"GET"},color:{blue:"#abd4f8",red:"#e97782"},message:{info:"Please enter a value in the search field!",warning:"Sorry, there are no images matching your search query. Please try again!",error:"Sorry, there are no connection to the server. Please try again later! ",exception:"Exception: We have some issue with connection. Please try again later! ",lastPage:"We're sorry, but you've reached the end of search results."},config:{params:{image_type:"photo",orientations:"horizontal",safesearch:!0,page:1,per_page:15}}};async function b(t,r){try{return c.fetchLoader(),e.config.params.key=e.API_KEY,e.config.params.q=t,e.config.params.page=r,(await h.get(e.BASE_URL,e.config)).data}catch(a){i(`${e.message.exception} ERROR: ${a.message}2`,e.color.red)}}const L=new v(".gallery a",{captionsData:"alt",captionDelay:250});function d(t){e.gallery.insertAdjacentHTML("beforeend",g(t)),L.refresh()}function g(t){return t.hits.map(({webformatURL:r,largeImageURL:a,tags:s,likes:o,views:n,comments:l,downloads:y})=>`
				<li class="gallery-item hvr-grow">
					<a class="gallery-link" href="${a}">
						<figure class="gallery-figure ">
							<img class="gallery-image" src="${r}" alt="${s}" loading="lazy">
							<figcaption class="gallery-figcaption">
								<ul class="img-content-wrapper">
									<li>Likes<span>${o}</span></li>
									<li>Views<span>${n}</span></li>
									<li>Comments<span>${l}</span></li>
									<li>Downloads<span>${y}</span></li>
								</ul>
							</figcaption>
						</figure>
					</a>
				</li>
		`).join("")}async function w(t,r){try{t===e.queryString&&e.eventType==="click"&&(e.currentPage+=1,r+=1);const a=await b(t,r);if(p(),f(a)){const s=Math.round(a.totalHits/r);d(a),m(s)}}catch(a){i(e.message.exception+a+3,e.color.red)}}function f(t){return t?t&&t.totalHits===0?(i(e.message.warning,e.color.blue),e.gallery.innerHTML="",!1):!0:(gallery.innerHTML="",!1)}function P(t=0,r=0){window.scrollBy({top:t,left:r,behavior:"smooth"})}function p(){document.querySelector(".loader-wrapper").remove()}function m(t){if(t<=e.config.params.per_page){e.loadMoreBtn.classList.remove("visible"),i(e.message.lastPage,e.color.blue);return}e.loadMoreBtn.classList.add("visible")}function S(){e.gallery.insertAdjacentHTML("beforeend",`<div class='loader-wrapper'>
        <div class='loader'></div>
    </div>`)}const c={fetchGallery:d,markup:g,renderGallery:w,validateGalleryData:f,scrollVertical:P,removeLoader:p,showHideBtn:m,fetchLoader:S};async function M(t){try{t.preventDefault();const r=t.target,a=r.elements.search.value.trim();if(e.eventType="submit",e.loadMoreBtn.classList.remove("visible"),u.destroy(),(e.queryString!==a||e.eventType==="submit")&&(e.gallery.innerHTML="",e.queryString=r.elements.search.value.trim(),e.currentPage=1),!a.trim()){i(e.message.info,e.color.blue),e.gallery.innerHTML="";return}await c.renderGallery(e.queryString,e.currentPage),r.reset()}catch(r){i(e.message.exception+r,e.color.red),e.gallery.innerHTML=""}}async function q(t){try{e.eventType="click",await c.renderGallery(e.queryString,e.currentPage);const r=document.querySelector("li"),{height:a}=r.getBoundingClientRect();c.scrollVertical(a*2,0)}catch(r){i(e.message.exception+r+1,e.color.red)}}e.form.addEventListener("submit",M);e.loadMoreBtn.addEventListener("click",q);
//# sourceMappingURL=index.js.map
